## install packages

In [7]:
#install.packages('keras')


In [8]:
#install.packages("tensorflow")

In [9]:
#install.packages("timetk")

In [29]:
library(keras)
library(tensorflow)
library(readxl)
library(ggplot2)
library(dplyr)
library(timetk)

In [15]:
GoldmanSachs = read.csv("/Users/korigray/Documents/GitHub/Final class project/Final-Project/GS.csv")

head(GoldmanSachs)

Date       Open    High    Low     Close   Adj.Close Volume  
1 1999-05-04 76.0000 77.2500 70.0000 70.3750 53.57680  22320900
2 1999-05-05 69.8750 69.8750 66.2500 69.1250 52.62515   7565700
3 1999-05-06 68.0000 69.3750 67.0625 67.9375 51.72110   2905700
4 1999-05-07 67.9375 74.8750 66.7500 74.1250 56.43165   4862300
5 1999-05-10 73.3750 73.5000 70.2500 70.6875 53.81471   2589400
6 1999-05-11 70.0000 71.1875 69.5000 70.6250 53.76712   1839800

In [16]:
scale_factors <- c(mean(GoldmanSachs$Adj.Close), sd(GoldmanSachs$Adj.Close))
scale_factors

[1] 140.67622  73.18767

In [17]:
scaled_train <- GoldmanSachs %>%
    dplyr::select(Adj.Close) %>%
    dplyr::mutate(Adj.Close = (Adj.Close - scale_factors[1]) / scale_factors[2])

head(scaled_train)

Adj.Close
1 -1.190083
2 -1.203086
3 -1.215439
4 -1.151076
5 -1.186833
6 -1.187483

In [18]:
prediction <- 12
lag <- prediction

In [19]:
scaled_train <- as.matrix(scaled_train)
 
# we lag the data 11 times and arrange that into columns
x_train_data <- t(sapply(
    1:(length(scaled_train) - lag - prediction + 1),
    function(x) scaled_train[x:(x + lag - 1), 1]
  ))
 
# now we transform it into 3D form
x_train_arr <- array(
    data = as.numeric(unlist(x_train_data)),
    dim = c(
        nrow(x_train_data),
        lag,
        1
    )
)

head(x_train_data)

x_train_arr

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]     
[1,] -1.190083 -1.203086 -1.215439 -1.151076 -1.186833 -1.187483 -1.157577
[2,] -1.203086 -1.215439 -1.151076 -1.186833 -1.187483 -1.157577 -1.160828
[3,] -1.215439 -1.151076 -1.186833 -1.187483 -1.157577 -1.160828 -1.192034
[4,] -1.151076 -1.186833 -1.187483 -1.157577 -1.160828 -1.192034 -1.208287
[5,] -1.186833 -1.187483 -1.157577 -1.160828 -1.192034 -1.208287 -1.208287
[6,] -1.187483 -1.157577 -1.160828 -1.192034 -1.208287 -1.208287 -1.201135
     [,8]      [,9]      [,10]     [,11]     [,12]    
[1,] -1.160828 -1.192034 -1.208287 -1.208287 -1.201135
[2,] -1.192034 -1.208287 -1.208287 -1.201135 -1.210887
[3,] -1.208287 -1.208287 -1.201135 -1.210887 -1.219990
[4,] -1.208287 -1.201135 -1.210887 -1.219990 -1.242744
[5,] -1.201135 -1.210887 -1.219990 -1.242744 -1.251196
[6,] -1.210887 -1.219990 -1.242744 -1.251196 -1.234942

, , 1

                 [,1]          [,2]          [,3]          [,4]          [,5]
   [1,] -1.1900833393 -1.2030861310 -1.2154386628 -1.1510760709 -1.1868326277
   [2,] -1.2030861310 -1.2154386628 -1.1510760709 -1.1868326277 -1.1874829012
   [3,] -1.2154386628 -1.1510760709 -1.1868326277 -1.1874829012 -1.1575768382
   [4,] -1.1510760709 -1.1868326277 -1.1874829012 -1.1575768382 -1.1608277548
   [5,] -1.1868326277 -1.1874829012 -1.1575768382 -1.1608277548 -1.1920340504
   [6,] -1.1874829012 -1.1575768382 -1.1608277548 -1.1920340504 -1.2082871984
   [7,] -1.1575768382 -1.1608277548 -1.1920340504 -1.2082871984 -1.2082871984
   [8,] -1.1608277548 -1.1920340504 -1.2082871984 -1.2082871984 -1.2011353651
   [9,] -1.1920340504 -1.2082871984 -1.2082871984 -1.2011353651 -1.2108873633
  [10,] -1.2082871984 -1.2082871984 -1.2011353651 -1.2108873633 -1.2199895525
  [11,] -1.2082871984 -1.2011353651 -1.2108873633 -1.2199895525 -1.2427440417
  [12,] -1.2011353651 -1.2108873633 -1.2199895525 -1.2427440417 -1.2511955475
  [13,] -1.2108873633 -1.2199895525 -1.2427440417 -1.2511955475 -1.2349423995
  [14,] -1.2199895525 -1.2427440417 -1.2511955475 -1.2349423995 -1.2173890187
  [15,] -1.2427440417 -1.2511955475 -1.2349423995 -1.2173890187 -1.2154386628
  [16,] -1.2511955475 -1.2349423995 -1.2173890187 -1.2154386628 -1.2544463958
  [17,] -1.2349423995 -1.2173890187 -1.2154386628 -1.2544463958 -1.2641982436
  [18,] -1.2173890187 -1.2154386628 -1.2544463958 -1.2641982436 -1.2602975318
  [19,] -1.2154386628 -1.2544463958 -1.2641982436 -1.2602975318 -1.2420941371
  [20,] -1.2544463958 -1.2641982436 -1.2602975318 -1.2420941371 -1.2362427415
  [21,] -1.2641982436 -1.2602975318 -1.2420941371 -1.2362427415 -1.2589973947
  [22,] -1.2602975318 -1.2420941371 -1.2362427415 -1.2589973947 -1.2407937951
  [23,] -1.2420941371 -1.2362427415 -1.2589973947 -1.2407937951 -1.2628978469
  [24,] -1.2362427415 -1.2589973947 -1.2407937951 -1.2628978469 -1.2641982436
  [25,] -1.2589973947 -1.2407937951 -1.2628978469 -1.2641982436 -1.2850024726
  [26,] -1.2407937951 -1.2628978469 -1.2641982436 -1.2850024726 -1.2693992974
  [27,] -1.2628978469 -1.2641982436 -1.2850024726 -1.2693992974 -1.2433940556
  [28,] -1.2641982436 -1.2850024726 -1.2693992974 -1.2433940556 -1.2459948489
  [29,] -1.2850024726 -1.2693992974 -1.2433940556 -1.2459948489 -1.2479452595
  [30,] -1.2693992974 -1.2433940556 -1.2459948489 -1.2479452595 -1.1991852142
  [31,] -1.2433940556 -1.2459948489 -1.2479452595 -1.1991852142 -1.2147885396
  [32,] -1.2459948489 -1.2479452595 -1.1991852142 -1.2147885396 -1.2459948489
  [33,] -1.2479452595 -1.1991852142 -1.2147885396 -1.2459948489 -1.2453448351
  [34,] -1.1991852142 -1.2147885396 -1.2459948489 -1.2453448351 -1.2329921939
  [35,] -1.2147885396 -1.2459948489 -1.2453448351 -1.2329921939 -1.2297415506
  [36,] -1.2459948489 -1.2453448351 -1.2329921939 -1.2297415506 -1.2173890187
  [37,] -1.2453448351 -1.2329921939 -1.2297415506 -1.2173890187 -1.1705795479
  [38,] -1.2329921939 -1.2297415506 -1.2173890187 -1.1705795479 -1.1855323949
  [39,] -1.2297415506 -1.2173890187 -1.1705795479 -1.1855323949 -1.1842323672
  [40,] -1.2173890187 -1.1705795479 -1.1855323949 -1.1842323672 -1.1887830929
  [41,] -1.1705795479 -1.1855323949 -1.1842323672 -1.1887830929 -1.2147885396
  [42,] -1.1855323949 -1.1842323672 -1.1887830929 -1.2147885396 -1.2225899769
  [43,] -1.1842323672 -1.1887830929 -1.2147885396 -1.2225899769 -1.2225899769
  [44,] -1.1887830929 -1.2147885396 -1.2225899769 -1.2225899769 -1.2108873633
  [45,] -1.2147885396 -1.2225899769 -1.2225899769 -1.2108873633 -1.2160887314
  [46,] -1.2225899769 -1.2225899769 -1.2108873633 -1.2160887314 -1.2186893608
  [47,] -1.2225899769 -1.2108873633 -1.2160887314 -1.2186893608 -1.2154386628
  [48,] -1.2108873633 -1.2160887314 -1.2186893608 -1.2154386628 -1.2141382115
  [49,] -1.2160887314 -1.2186893608 -1.2154386628 -1.2141382115 -1.1998353784
  [50,] -1.2186893608 -1.2154386628 -1.2141382115 -1.1998353784 -1.2134881020
  [51,] -1.2154

In [20]:

y_train_data <- t(sapply(
    (1 + lag):(length(scaled_train) - prediction + 1),
    function(x) scaled_train[x:(x + prediction - 1)]
))
 
y_train_arr <- array(
    data = as.numeric(unlist(y_train_data)),
    dim = c(
        nrow(y_train_data),
        prediction,
        1
    )
)

head(y_train_data)
     

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]     
[1,] -1.210887 -1.219990 -1.242744 -1.251196 -1.234942 -1.217389 -1.215439
[2,] -1.219990 -1.242744 -1.251196 -1.234942 -1.217389 -1.215439 -1.254446
[3,] -1.242744 -1.251196 -1.234942 -1.217389 -1.215439 -1.254446 -1.264198
[4,] -1.251196 -1.234942 -1.217389 -1.215439 -1.254446 -1.264198 -1.260298
[5,] -1.234942 -1.217389 -1.215439 -1.254446 -1.264198 -1.260298 -1.242094
[6,] -1.217389 -1.215439 -1.254446 -1.264198 -1.260298 -1.242094 -1.236243
     [,8]      [,9]      [,10]     [,11]     [,12]    
[1,] -1.254446 -1.264198 -1.260298 -1.242094 -1.236243
[2,] -1.264198 -1.260298 -1.242094 -1.236243 -1.258997
[3,] -1.260298 -1.242094 -1.236243 -1.258997 -1.240794
[4,] -1.242094 -1.236243 -1.258997 -1.240794 -1.262898
[5,] -1.236243 -1.258997 -1.240794 -1.262898 -1.264198
[6,] -1.258997 -1.240794 -1.262898 -1.264198 -1.285002

In [21]:
x_test <- GoldmanSachs$Adj.Close[(nrow(scaled_train) - prediction + 1):nrow(scaled_train)]

x_test

[1] 333.59 329.90 327.00 324.98 329.16 340.76 343.27 345.38 339.00 343.01
[11] 335.61 336.23

In [22]:
# scale the data with same scaling factors as for training
x_test_scaled <- (x_test - scale_factors[1]) / scale_factors[2]
 
# this time our array just has one sample, as we intend to perform one 12-months prediction
x_pred_arr <- array(
    data = x_test_scaled,
    dim = c(
        1,
        lag,
        1
    )
)

x_pred_arr
     

, , 1

         [,1]    [,2]     [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
[1,] 2.635878 2.58546 2.545836 2.518236 2.575349 2.733846 2.768141 2.796971
         [,9]    [,10]    [,11]   [,12]
[1,] 2.709798 2.764589 2.663478 2.67195

In [19]:
#reticulate::py_config()

In [20]:
#Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python3")

In [21]:
#remove.packages("reticulate")

In [22]:
#install.packages("remotes")


The downloaded binary packages are in
	/var/folders/58/w1zyx47n4n535hjht6vsjd240000gn/T//Rtmpb2iSE2/downloaded_packages


In [23]:
library("reticulate")

In [24]:
lstm_model <- keras_model_sequential()
 
lstm_model %>%
  layer_lstm(units = 50, # size of the layer
       batch_input_shape = c(1, 12, 1), # batch size, timesteps, features
       return_sequences = TRUE,
       stateful = TRUE) %>%
  # fraction of the units to drop for the linear transformation of the inputs
  layer_dropout(rate = 0.5) %>%
  layer_lstm(units = 50,
        return_sequences = TRUE,
        stateful = TRUE) %>%
  layer_dropout(rate = 0.5) %>%
  time_distributed(keras::layer_dense(units = 1))

lstm_model
     

List of 20
 $ python              : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate/bin/python"
 $ libpython           : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate/lib/libpython3.8.dylib"
 $ pythonhome          : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate:/Users/korigray/Library/r-miniconda/envs/r-reticulate"
 $ pythonpath          : chr "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/config:/Users/korigray/Library/r-mini"| __truncated__
 $ prefix              : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate"
 $ exec_prefix         : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate"
 $ base_exec_prefix    : chr "/Users/korigray/Library/r-miniconda/envs/r-reticulate"
 $ virtualenv          : chr ""
 $ virtualenv_activate : chr ""
 $ version_string      : chr "3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:05:36)  [Clang 14.0.6 ]"
 $ version             : chr "3.8"
 $ architecture   

ERROR: Error: Python module tensorflow.keras was not found.

Detected Python configuration:





In [ ]:
lstm_model %>%
    compile(loss = 'mae', optimizer = 'adam', metrics = 'accuracy')
 
summary(lstm_model)

In [ ]:
lstm_model %>% fit(
    x = x_train_arr,
    y = y_train_arr,
    batch_size = 1,
    epochs = 20,
    verbose = 0,
    shuffle = FALSE
)

In [ ]:
lstm_forecast <- lstm_model %>%
    predict(x_pred_arr, batch_size = 1) %>%
    .[, , 1]
 
# we need to rescale the data to restore the original values
lstm_forecast <- lstm_forecast * scale_factors[2] + scale_factors[1]

lstm_forecast
     

In [ ]:
fitted <- predict(lstm_model, x_train_arr, batch_size = 1) %>%
     .[, , 1]

fitted
     

In [ ]:
if (dim(fitted)[2] > 1) {
    fit <- c(fitted[, 1], fitted[dim(fitted)[1], 2:dim(fitted)[2]])
} else {
    fit <- fitted[, 1]
}
 
# additionally we need to rescale the data
fitted <- fit * scale_factors[2] + scale_factors[1]
nrow(fitted) # 562
     

In [ ]:

# I specify first forecast values as not available
fitted <- c(rep(NA, lag), fitted)

In [ ]:
lstm_forecast <- timetk::tk_ts(lstm_forecast,
    start = c(2021, 5),
    end = c(2022, 4),
    frequency = 12
)

lstm_forecast
     


In [ ]:
input_ts <- timetk::tk_ts(economics$unemploy, 
    start = c(1999, 7), 
    end = c(2021, 4), 
    frequency = 12)
     

In [ ]:
forecast_list <- list(
    model = NULL,
    method = "LSTM",
    mean = lstm_forecast,
    x = input_ts,
    fitted = fitted,
    residuals = as.numeric(input_ts) - as.numeric(fitted)
  )
 
class(forecast_list) <- "forecast"

In [ ]:
forecast::autoplot(forecast_list)


In [28]:
#library(reticulate)
#use_python("/Users/korigray/miniconda3/bin/python3.10")
#py_config()

In [25]:
#library(reticulate)

In [26]:
#py_config()

In [27]:
#use_python("/usr/bin/python3")

In [ ]:
#/Users/korigray/miniconda3/bin/python3.10


In [30]:
-march=native -mtune=native -O3

ERROR: Error in eval(expr, envir, enclos): object 'native' not found
